services:
  - type: web
    name: personal-site
    env: static
    buildCommand: echo "Static site - no build required"
    staticPublishPath: .
    envVars:
      - key: NODE_ENV
        value: production
    autoDeploy: true
    branch: main 